"""Interactive ``.env`` generator (``opencode-talk-bridge --init``).

Prompts for the essential settings and writes a ``.env`` (chmod 600, since it
holds the app password). Advanced options (streaming, STT/TTS, scheduler) keep
their defaults and can be added later from ``.env.example``. Input functions are
injectable so the flow is unit-testable.
"""

from __future__ import annotations

import getpass
import os
import sys
from collections.abc import Callable

# (key, label, default, required, secret) — order preserved in the written file.
_FIELDS: list[tuple[str, str, str, bool, bool]] = [
    ("NC_URL", "Nextcloud base URL (https://…)", "", True, False),
    ("NC_USER", "Nextcloud username", "", True, False),
    ("NC_APP_PASSWORD", "Nextcloud app password (hidden)", "", True, True),
    (
        "TALK_CONVERSATIONS",
        "Talk conversation token(s) to watch (comma-separated, or 'all')",
        "",
        True,
        False,
    ),
    ("ALLOWED_USERS", "Allowed Talk user IDs (comma-separated logins)", "", True, False),
    ("OPENCODE_URL", "OpenCode server URL", "http://127.0.0.1:4096", False, False),
    ("OPENCODE_USERNAME", "OpenCode Basic-Auth user (blank if unsecured)", "", False, False),
    ("OPENCODE_PASSWORD", "OpenCode Basic-Auth password (blank if unsecured)", "", False, True),
    ("SHARE_WEBDAV_DIR", "WebDAV folder for code/TTS attachments (blank to disable)", "", False, False),
    ("BOT_LOCALE", "UI language (de/en)", "de", False, False),
]


def _is_url(value: str) -> bool:
    return value.startswith("http://") or value.startswith("https://")


def run_init(
    env_path: str = ".env",
    *,
    ask: Callable[[str], str] | None = None,
    ask_secret: Callable[[str], str] | None = None,
    out: Callable[[str], None] | None = None,
    confirm: Callable[[str], bool] | None = None,
) -> int:
    ask = ask or input
    ask_secret = ask_secret or getpass.getpass
    out = out or print
    confirm = confirm or _default_confirm

    if not _interactive(ask):
        out("--init requires an interactive terminal.")
        return 2

    if os.path.exists(env_path) and not confirm(f"{env_path} exists — overwrite?"):
        out("Aborted; existing file kept.")
        return 1

    out("Setting up opencode-talk-bridge. Press Enter to accept a [default].\n")
    values: dict[str, str] = {}
    for key, label, default, required, secret in _FIELDS:
        validate = _is_url if key in ("NC_URL", "OPENCODE_URL") else None
        values[key] = _prompt(ask, ask_secret, out, label, default, required, secret, validate)

    _write_env(env_path, values)
    out(f"\n✅ Wrote {env_path} (chmod 600).")
    out("Next: `opencode-talk-bridge --check`, then `opencode-talk-bridge`.")
    out("More options (streaming, STT/TTS, scheduler) are documented in .env.example.")
    return 0


def _prompt(
    ask: Callable[[str], str],
    ask_secret: Callable[[str], str],
    out: Callable[[str], None],
    label: str,
    default: str,
    required: bool,
    secret: bool,
    validate: Callable[[str], bool] | None,
) -> str:
    suffix = f" [{default}]" if default else ""
    while True:
        raw = ask_secret(f"{label}: ") if secret else ask(f"{label}{suffix}: ")
        value = raw.strip() or default
        if not value:
            if required:
                out("  → required, please enter a value.")
                continue
            return ""
        if validate and not validate(value):
            out("  → must start with http:// or https://")
            continue
        return value


def _write_env(env_path: str, values: dict[str, str]) -> None:
    lines = ["# opencode-talk-bridge configuration (generated by --init).", ""]
    for key, _label, _default, _required, _secret in _FIELDS:
        lines.append(f"{key}={values.get(key, '')}")
    content = "\n".join(lines) + "\n"
    # Write 0600 from the start so the app password is never world-readable.
    fd = os.open(env_path, os.O_WRONLY | os.O_CREAT | os.O_TRUNC, 0o600)
    with os.fdopen(fd, "w", encoding="utf-8") as fh:
        fh.write(content)
    os.chmod(env_path, 0o600)


def _interactive(ask: Callable[[str], str]) -> bool:
    # Only enforce a real TTY for the built-in input(); injected asks pass.
    return ask is not input or sys.stdin.isatty()


def _default_confirm(question: str) -> bool:
    return input(f"{question} [y/N] ").strip().lower() in ("y", "yes", "j", "ja")
